-- PostgreSQL Database Schema for Municipalidad de Concordia - Sistema de Incidencias

DROP TABLE IF EXISTS incidencias_estados CASCADE;
DROP TABLE IF EXISTS incidencias CASCADE;
DROP TABLE IF EXISTS estados CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS articulos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS areas CASCADE;

CREATE TABLE public.areas (
    id_area integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion character varying(250) NOT NULL,
    activo smallint DEFAULT 1 NOT NULL
);

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion character varying(255) NOT NULL,
    activo smallint DEFAULT 1 NOT NULL
);

CREATE TABLE public.articulos (
    id_articulo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area integer NOT NULL,
    id_categoria integer NOT NULL,
    descripcion character varying(250) NOT NULL,
    activo smallint DEFAULT 1 NOT NULL,
    CONSTRAINT articulos_id_area_fkey FOREIGN KEY (id_area) REFERENCES public.areas(id_area),
    CONSTRAINT articulos_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria)
);

CREATE TABLE public.estados (
    id_estado integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion character varying(255) NOT NULL,
    activo smallint DEFAULT 1 NOT NULL
);

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_area integer NOT NULL,
    nombres character varying(250) NOT NULL,
    apellidos character varying(250) NOT NULL,
    usuario character varying(255) NOT NULL UNIQUE,
    contrasenia character varying(255) NOT NULL,
    avatar character varying(255) NOT NULL DEFAULT '',
    rol integer NOT NULL,
    activo smallint DEFAULT 1 NOT NULL,
    CONSTRAINT usuarios_id_area_fkey FOREIGN KEY (id_area) REFERENCES public.areas(id_area)
);

CREATE TABLE public.incidencias (
    id_incidencia integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_articulo integer NOT NULL,
    id_estado integer NOT NULL,
    creado_por integer NOT NULL,
    asignado_a integer NOT NULL DEFAULT 0,
    creado timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    prioridad integer DEFAULT 1 NOT NULL,
    descripcion_pedido character varying(250),
    descripcion_resolucion character varying(250),
    CONSTRAINT incidencias_id_articulo_fkey FOREIGN KEY (id_articulo) REFERENCES public.articulos(id_articulo),
    CONSTRAINT incidencias_id_estado_fkey FOREIGN KEY (id_estado) REFERENCES public.estados(id_estado),
    CONSTRAINT incidencias_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.usuarios(id_usuario)
);

CREATE TABLE public.incidencias_estados (
    id_pedidos_estados integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia integer NOT NULL,
    id_estado integer NOT NULL,
    fecha_hora_estado time with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT incidencias_estados_id_incidencia_fkey FOREIGN KEY (id_incidencia) REFERENCES public.incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT incidencias_estados_id_estado_fkey FOREIGN KEY (id_estado) REFERENCES public.estados(id_estado)
);
